name: kuzzle
version: 2.0.0-alpha.1

description: A library to interact with kuzzle API. A backend software, self-hostable and ready to use to power modern cross-platform apps.
authors:
- Priyanshu Jindal<priyanshujindal1995@gmail.com>
- Sacha Stafyniak<sacha.stafyniak@gmail.com>
- Manuel Baun<manuel.baun@gmail.com>

homepage: https://github.com/prijindal/kuzzle_dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  pedantic: ^1.9.0
  meta: ^1.1.8
  uuid: ^2.0.4

dev_dependencies:
  test: ^1.14.2
  coverage: ^0.13.9
